common:
  htmlUrl: http://1957anti.ru
develop:
  token: "685334324:AAHt11-YCvjJmDR4Ay1PMrQE9yQQD4DZ4Kg"
  chatId: "@anti1957_dev"
  # интервал проверки новых сообщений в секундах
  checkInterval: 60
production:
  token: "685334324:AAHt11-YCvjJmDR4Ay1PMrQE9yQQD4DZ4Kg"
  chatId: "@ru_1957anti"
  # интервал проверки новых сообщений в секундах
  checkInterval: 300
