common:
  htmlUrl: http://1957anti.ru/publications
develop:
  token: "685334324:AAHt11-YCvjJmDR4Ay1PMrQE9yQQD4DZ4Kg"
  chatId: "@1957anti_dev"
  # интервал проверки новых сообщений в секундах
  checkInterval: 60
production:
  token: "685334324:AAHt11-YCvjJmDR4Ay1PMrQE9yQQD4DZ4Kg"
  chatId: "@1957anti"
  # интервал проверки новых сообщений в секундах
  checkInterval: 300
